### ISSUE TITLE
ruTorrent fix

### ISSUE THREAD

**Issue by wimh** [thefinn93/CCC-torrent-feed#1]
I could fix the ruTorrent issue by adding `xml_base=''` to the [AtomFeed.add](http://werkzeug.pocoo.org/docs/0.11/contrib/atom/#werkzeug.contrib.atom.AtomFeed.add) function.

Looking at [rss.php#L241](https://github.com/Novik/ruTorrent/blob/master/plugins/rss/rss.php#L241), it looks like a bug. It prefixes `xml:base` to every url, even if it is not relative. (And even if a `xml:base` does not exist for a particular entry). But the fix is easy, don't use `xml:base`, you don't need it anyway.

https://tools.ietf.org/html/rfc4287

> Any element defined by this specification MAY have an xml:base
> attribute [W3C.REC-xmlbase-20010627].  When xml:base is used in an
> Atom Document, it serves the function described in section 5.1.1 of
> [RFC3986], establishing the base URI (or IRI) for resolving any
> relative references found within the effective scope of the xml:base
> attribute.

Your `mktime` function was not working for me. I don't know exactly why, but I have fixed it in a [different way](http://stackoverflow.com/a/1697907). If you need more details, or a pull request, let me know.

**Comment by thefinn93** [comment]
+1 if you wanna do a couple of pull requests, I'd rather be lazy than write the code :P please break the ruTorrent one and the time one up into separate PRs though, if you do them. Thanks for the feedback!

**Comment by wimh** [comment]
Created pull request #2 which is merged meanwhile.

I created #3 and #4 to show my other issues. I leave it up to you whether you merge those or not. Both are related to python 2.7. Using python 3.2 failed too

```
File "/home/wh/src/CCC-torrent-feed/venv/lib/python3.2/site-packages/werkzeug/exceptions.py", line 113
  return u'<p>%s</p>' % escape(self.description)
                    ^
SyntaxError: invalid syntax
```

I chose to fix the other error. (I am not a python expert).
